### ISSUE TITLE
unknown directive "google" in /etc/nginx/conf.d/google.conf:22

### ISSUE THREAD

**Issue by kelvinblood** [brentybh/onemirror#2]
你好，好奇你有没有遇到整个错误？

```
Executing busybox-1.25.1-r2.trigger
OK: 10 MiB in 24 packages
Removing intermediate container beac183302b7
 ---> 982586bb6c29
Step 9/13 : COPY nginx /etc/nginx/
 ---> 7d678f7cd815
Step 10/13 : RUN nginx -t
 ---> Running in a50454d820bb
2019/01/12 06:52:00 [emerg] 6#6: unknown directive "google" in /etc/nginx/conf.d/google.conf:22
nginx: [emerg] unknown directive "google" in /etc/nginx/conf.d/google.conf:22
nginx: configuration file /etc/nginx/nginx.conf test failed
The command '/bin/sh -c nginx -t' returned a non-zero code: 1
```

仅仅是folk了你的源码然后 build，并没有做更多的东西。

**Comment by kuangjy2** [comment]
同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
系统是Debian 9

**Comment by kelvinblood** [comment]
> 同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
> 系统是Debian 9

这个错误应该是系统找到的是另一个nginx，而不是编译的这个nginx，只要找到了就好。
你本地编译前先把老nginx去掉应该就好了。

**Comment by kuangjy2** [comment]
> > 同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
> > 系统是Debian 9
> 
> 这个错误应该是系统找到的是另一个nginx，而不是编译的这个nginx，只要找到了就好。
> 你本地编译前先把老nginx去掉应该就好了。

不不不，第一次用1.10是直接apt install nginx的，然后下载对应版本的源码增加模块参数重新编译再覆盖/usr/sbin/nginx的，第二次是装的裸系统下载1.14源码make & make install的，第三次就是用裸系统配docker直接跑的这个镜像的，docker build都过不了，裸系统本身就不存在nginx，你跑一下nginx -V看看编译参数就知道是不是自己编译的二进制文件了

**Comment by kuangjy2** [comment]
> > 同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
> > 系统是Debian 9
> 
> 这个错误应该是系统找到的是另一个nginx，而不是编译的这个nginx，只要找到了就好。
> 你本地编译前先把老nginx去掉应该就好了。

裸机安装ngx_http_google_filter_module已解决，换成nginx 1.8.1就可以，应该是ngx_http_google_filter_module不兼容高版本nginx，这个docker镜像可以修改下nginx版本，编译参数也需要做一下相应修改

**Comment by kelvinblood** [comment]
> > > 同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
> > > 系统是Debian 9
> > 
> > 
> > 这个错误应该是系统找到的是另一个nginx，而不是编译的这个nginx，只要找到了就好。
> > 你本地编译前先把老nginx去掉应该就好了。
> 
> 裸机安装ngx_http_google_filter_module已解决，换成nginx 1.8.1就可以，应该是ngx_http_google_filter_module不兼容高版本nginx，这个docker镜像可以修改下nginx版本，编译参数也需要做一下相应修改

docker 镜像这个不知道是什么问题。
我看了作者编译的镜像，也是1.13.12的，能运行。

针对我容器化build的问题应该是其他原因。。

**Comment by kuangjy2** [comment]
> > > > 同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
> > > > 系统是Debian 9
> > > 
> > > 
> > > 这个错误应该是系统找到的是另一个nginx，而不是编译的这个nginx，只要找到了就好。
> > > 你本地编译前先把老nginx去掉应该就好了。
> > 
> > 
> > 裸机安装ngx_http_google_filter_module已解决，换成nginx 1.8.1就可以，应该是ngx_http_google_filter_module不兼容高版本nginx，这个docker镜像可以修改下nginx版本，编译参数也需要做一下相应修改
> 
> docker 镜像这个不知道是什么问题。
> 我看了作者编译的镜像，也是1.13.12的，能运行。
> 
> 针对我容器化build的问题应该是其他原因。。

跟nginx版本有关没跑了，1.8.1是最后一个没支持dynamic module的版本，你可以自己改一下dockerfile里的nginx版本然后把编译参数跟dynamic module相关的去掉试试。docker跟本机系统应该是没有关系的

**Comment by kelvinblood** [comment]
> > > > > 同错误，我一开始是裸系统用ngx_http_google_filter_module模块编译安装nginx配置的，然后报这个错，之后百度到这个docker镜像，依然报这个错
> > > > > 系统是Debian 9
> > > > 
> > > > 
> > > > 这个错误应该是系统找到的是另一个nginx，而不是编译的这个nginx，只要找到了就好。
> > > > 你本地编译前先把老nginx去掉应该就好了。
> > > 
> > > 
> > > 裸机安装ngx_http_google_filter_module已解决，换成nginx 1.8.1就可以，应该是ngx_http_google_filter_module不兼容高版本nginx，这个docker镜像可以修改下nginx版本，编译参数也需要做一下相应修改
> > 
> > 
> > docker 镜像这个不知道是什么问题。
> > 我看了作者编译的镜像，也是1.13.12的，能运行。
> > 针对我容器化build的问题应该是其他原因。。
> 
> 跟nginx版本有关没跑了，1.8.1是最后一个没支持dynamic module的版本，你可以自己改一下dockerfile里的nginx版本然后把编译参数跟dynamic module相关的去掉试试。docker跟本机系统应该是没有关系的

作者编译的没问题，我在直接用作者的跑，是1.13.12的nginx.

**Comment by maxduke** [comment]
直接用ngx_http_google_filter_modul重新编译nginx成功，但也报同样错误，用了1.8.1正常

**Comment by bohanwood** [comment]
来了，这个东西太久没管了
主要就是依赖 google nginx 模块的
有时间更新一下

**Comment by bohanwood** [comment]
已确认，应该是模块 bug 吧

**Comment by bohanwood** [comment]
不想折腾这个了……
换了几个版本都编译不通……

**Comment by kuangjy2** [comment]
> 不想折腾这个了……
> 换了几个版本都编译不通……

好奇你docker库的镜像怎么编译的

**Comment by bohanwood** [comment]
> > 不想折腾这个了……
> > 换了几个版本都编译不通……
> 
> 好奇你docker库的镜像怎么编译的

旧版 nginx 旧版 google 模块
因为我当时直接用的 master 分支所以可能要找一找具体是 google 模块仓库的哪个commit

**Comment by kelvinblood** [comment]
> 不想折腾这个了……
> 换了几个版本都编译不通……

蛤蛤蛤。没事，我反正用着你的老镜像。

**Comment by bohanwood** [comment]
初试成功，有望更新

**Comment by bohanwood** [comment]
勉强将 nginx 升级至 stable 线最新版，openssl 最新稳定版，
修复 google scholar 搜索
稍后发布 release

**Comment by bohanwood** [comment]
@kelvinblood 已发布更新 v1.5，
更新了上游 Dockerfile，
Alpine 3.9 系统，
NGINX 稳定版 1.14.x（应该是可兼容的最新版本），
OpenSSL 1.1.1（支持最新 TLS 1.3），
指明了模块的确切 commit hash，
可正常使用谷歌学术。
现在自行编译仓库里的代码应该没有问题了
